# Generated by Django 5.1.6 on 2025-02-28 14:40

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='main_image', verbose_name='Image')),
                ('name', models.CharField(max_length=255, verbose_name='Company name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phonenumber')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('facebook', models.URLField(verbose_name='facebook')),
                ('youtube', models.URLField(verbose_name='youtube')),
                ('linkedin', models.URLField(verbose_name='linkedin')),
            ],
            options={
                'verbose_name': 'Main Info',
                'verbose_name_plural': 'Main Info',
            },
        ),
    ]
