# Generated by Django 5.1.6 on 2025-03-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=255, verbose_name='part1')),
                ('text2', models.CharField(max_length=255, verbose_name='part2')),
                ('text3', models.CharField(max_length=255, verbose_name='part3')),
                ('text4', models.CharField(max_length=255, verbose_name='part4')),
                ('but_text', models.CharField(max_length=255, verbose_name='Button text')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
