# Generated by Django 5.1.6 on 2025-03-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homestatus_imagecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecycle',
            name='img',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
