# Generated by Django 5.1.6 on 2025-03-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_imagecycle_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecycle',
            name='img',
        ),
        migrations.AddField(
            model_name='imagecycle',
            name='img1',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Image cycle1'),
        ),
        migrations.AddField(
            model_name='imagecycle',
            name='img2',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Image cycle2'),
        ),
    ]
