# Generated by Django 5.1.6 on 2025-03-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_imagecycle_img_imagecycle_img1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_icon', models.ImageField(upload_to='icons', verbose_name='property_icon')),
                ('property_name', models.CharField(max_length=30, verbose_name='property_name')),
                ('availability', models.IntegerField(verbose_name='availability')),
            ],
        ),
    ]
