# Generated by Django 5.1.6 on 2025-03-01 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='img')),
                ('text1', models.CharField(max_length=255, verbose_name='text1')),
                ('text2', models.CharField(max_length=255, verbose_name='text2')),
            ],
        ),
        migrations.CreateModel(
            name='SubMoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.CharField(max_length=255, verbose_name='Lines')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moreinfo_rn', to='main.moreinfo')),
            ],
        ),
    ]
