# Generated by Django 5.1.6 on 2025-03-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_moreinfo_submoreinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='image')),
                ('goal', models.CharField(max_length=255, verbose_name='For rent/sell?')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('info', models.CharField(max_length=255, verbose_name='About property')),
                ('adress', models.CharField(max_length=255, verbose_name='Adress')),
                ('teritory', models.IntegerField(verbose_name='teritory(sqmt)')),
                ('bedrooms', models.IntegerField(verbose_name='bedrooms number')),
                ('bathrooms', models.IntegerField(verbose_name='bathrooms number')),
            ],
        ),
    ]
