# Generated by Django 5.1.6 on 2025-03-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_propertylisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentImg', models.ImageField(upload_to='images', verbose_name='AgentImage')),
                ('text1', models.CharField(max_length=255, verbose_name='text1')),
                ('text2', models.CharField(max_length=255, verbose_name='text2')),
            ],
        ),
    ]
