# Generated by Django 5.1.6 on 2025-03-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contactagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAgents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='AgentImg')),
                ('name', models.CharField(max_length=50, verbose_name='Full name')),
                ('designation', models.CharField(max_length=30, verbose_name='Designation')),
                ('facebook', models.URLField(verbose_name='FaceBook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('instagram', models.URLField(verbose_name='Instagram')),
            ],
        ),
    ]
