# Generated by Django 5.1.6 on 2025-03-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_propertyagents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOpinions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Client name')),
                ('img', models.ImageField(upload_to='images', verbose_name='ClientImg')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('profession', models.CharField(max_length=30, verbose_name='Profession')),
            ],
        ),
    ]
